import { Property } from '@/types/property'

// Mock data for demonstration
// In production, this would come from your CMS or database
export const mockProperties: Property[] = [
    {
        id: '1',
        slug: 'apartamento-jardins-3-quartos',
        title: 'Apartamento Premium em Jardins',
        description: 'Apartamento de alto padrão com acabamento premium, localizado em uma das regiões mais valorizadas da cidade. Vista panorâmica, varanda gourmet e infraestrutura completa.',
        type: 'apartment',
        status: 'lancamento',
        purpose: 'moradia',
        city: 'São Paulo',
        neighborhood: 'Jardins',
        bedrooms: 3,
        bathrooms: 3,
        parkingSpots: 2,
        area: 145,
        price: 1850000,
        priceOnRequest: false,
        images: [
            {
                url: '/images/properties/living-room.png',
                alt: 'Sala de estar',
                width: 1200,
                height: 800,
                isPrimary: true,
            },
        ],
        features: [
            'Varanda gourmet',
            'Piso porcelanato',
            'Ar condicionado',
            'Armários planejados',
            'Churrasqueira',
        ],
        technicalAnalysisAvailable: true,
        isStrategicAsset: true,
        marketContext: 'Região com alta valorização nos últimos 5 anos. Proximidade a comércio, serviços e transporte público.',
        idealBuyerProfile: 'Executivos e profissionais liberais que buscam qualidade de vida e valorização patrimonial.',
        builderId: '1',
        builderName: 'Construtora Premium',
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-01-15'),
        featured: true,
    },
    {
        id: '2',
        slug: 'casa-condominio-alphaville',
        title: 'Casa em Condomínio Fechado - Alphaville',
        description: 'Casa moderna em condomínio de alto padrão com segurança 24h, área de lazer completa e localização privilegiada.',
        type: 'house',
        status: 'usado',
        purpose: 'moradia',
        city: 'Barueri',
        neighborhood: 'Alphaville',
        bedrooms: 4,
        bathrooms: 4,
        parkingSpots: 4,
        area: 380,
        price: 2500000,
        priceOnRequest: false,
        images: [
            {
                url: '/images/properties/house-facade.png',
                alt: 'Fachada da casa',
                width: 1200,
                height: 800,
                isPrimary: true,
            },
        ],
        features: [
            'Piscina',
            'Churrasqueira',
            'Jardim',
            'Home office',
            'Aquecimento solar',
        ],
        technicalAnalysisAvailable: true,
        isStrategicAsset: false,
        marketContext: 'Condomínio consolidado com boa liquidez. Infraestrutura completa e valorização constante.',
        idealBuyerProfile: 'Famílias que buscam espaço, segurança e qualidade de vida.',
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-01-10'),
        featured: true,
    },
    {
        id: '3',
        slug: 'sala-comercial-faria-lima',
        title: 'Sala Comercial - Faria Lima',
        description: 'Sala comercial em edifício corporativo classe A, com infraestrutura completa e localização estratégica.',
        type: 'commercial',
        status: 'usado',
        purpose: 'investimento',
        city: 'São Paulo',
        neighborhood: 'Faria Lima',
        bedrooms: 0,
        bathrooms: 2,
        parkingSpots: 3,
        area: 95,
        price: 980000,
        priceOnRequest: false,
        images: [
            {
                url: '/images/properties/apartment-building.png',
                alt: 'Sala comercial',
                width: 1200,
                height: 800,
                isPrimary: true,
            },
        ],
        features: [
            'Piso elevado',
            'Ar condicionado central',
            'Gerador',
            'Segurança 24h',
            'Recepção',
        ],
        technicalAnalysisAvailable: true,
        isStrategicAsset: true,
        marketContext: 'Região prime com alta demanda de locação. Rentabilidade atrativa para investidores.',
        idealBuyerProfile: 'Investidores que buscam renda passiva em localização premium.',
        createdAt: new Date('2024-01-12'),
        updatedAt: new Date('2024-01-12'),
        featured: false,
    },
]
